Unipet/Models/Contato.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Unipet.Models
{
    [Table("Contato")]
    public class Contato
    {
        [Key]
        public int IdContato { get; set; }

        [Required(ErrorMessage = "O campo NOME é obrigatório")]
        [StringLength(50, ErrorMessage = "O nome deve possuir no máximo 50 caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O campo ASSUNTO é obrigatório")]
        [StringLength(100, ErrorMessage = "O assunto deve possuir no máximo 100 caracteres")]
        public string Assunto { get; set; }

        [Required(ErrorMessage = "O campo E-MAIL é obrigatório")]
        [StringLength(100, ErrorMessage = "O e-mail deve possuir no máximo 100 caracteres")]
        public string Email { get; set; }

        [StringLength(20, ErrorMessage = "O telefone deve possuir no máximo 20 caracteres")]
        public string Telefone { get; set; }

        [StringLength(20, ErrorMessage = "O celular deve possuir no máximo 20 caracteres")]
        public string Celular { get; set; }

        [Required(ErrorMessage = "O campo MENSAGEM é obrigatório")]
        [StringLength(1000, ErrorMessage = "A mensagem deve possuir no máximo 1000 caracteres")]
        public string Mensagem { get; set; }
    }
}

Unipet/Controllers/ContatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Unipet.Data;
using Unipet.Models;
using Unipet.Services;

namespace Unipet.Controllers
{
    public class ContatosController : Controller
    {
        private readonly Context _context;
        private readonly int pageSize = 10;

        public ContatosController(Context context)
        {
            _context = context;
        }

        // GET: Contatos
        public ActionResult Index()
        {
            var contatos = PaginatedList<Contato>.Create(_context.Contatos.AsQueryable(), 1, pageSize);
            return View(contatos);
        }

        [HttpGet]
        public PartialViewResult GetGrid(string sortOrder, string searchString, int? pageNumber)
        {
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            //ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["CurrentFilter"] = searchString;

            var contatos = _context.Contatos.AsQueryable();

            if (!String.IsNullOrEmpty(searchString))
            {
                contatos = contatos.Where(s => s.Nome.Contains(searchString)
                                          || s.Assunto.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    contatos = contatos.OrderByDescending(s => s.Nome);
                    break;
                //case "Date":
                //    contatos = contatos.OrderBy(s => s.DataCadastro);
                //    break;
                //case "date_desc":
                //    contatos = contatos.OrderByDescending(s => s.Data);
                //    break;
                default:
                    contatos = contatos.OrderBy(s => s.Nome);
                    break;
            }

            var retorno = PaginatedList<Contato>.Create(contatos, pageNumber ?? 1, pageSize);
            return PartialView("_Grid", retorno);
        }

        // GET: Contatos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contato = await _context.Contatos
                .FirstOrDefaultAsync(m => m.IdContato == id);
            if (contato == null)
            {
                return NotFound();
            }

            return View(contato);
        }

        // GET: Contatos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contatos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdContato,Nome,Assunto,Email,Telefone,Celular,Mensagem")] Contato contato)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contato);
                await _context.SaveChangesAsync();
                return Ok();
            }
            return BadRequest("Preencha o formulario para enviar o seu contato!");
        }

        // GET: Contatos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contato = await _context.Contatos.FindAsync(id);
            if (contato == null)
            {
                return NotFound();
            }
            return View(contato);
        }

        // POST: Contatos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdContato,Nome,Assunto,Email,Telefone,Celular,Mensagem")] Contato contato)
        {
            if (id != contato.IdContato)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contato);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContatoExists(contato.IdContato))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contato);
        }

        // GET: Contatos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contato = await _context.Contatos
                .FirstOrDefaultAsync(m => m.IdContato == id);
            if (contato == null)
            {
                return NotFound();
            }

            return View(contato);
        }

        // POST: Contatos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contato = await _context.Contatos.FindAsync(id);
            _context.Contatos.Remove(contato);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContatoExists(int id)
        {
            return _context.Contatos.Any(e => e.IdContato == id);
        }
    }
}

Unipet/Views/Contatos/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="app-wrapper">
    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="container-xl">
            <!--card Boas Vindas-->
            <div class="app-card alert alert-dismissible shadow-sm mb-4 border-left-decoration" role="alert">
                <div class="inner">
                    <div class="app-card-body p-3 p-lg-4">
                        <h3 class="mb-3">Contatos</h3>
                        <div class="row gx-5 gy-3">
                            <form class="mb-3" data-ajax="true" data-ajax-method="get" data-ajax-update="#Grid"
                                  data-ajax-mode="replace" data-ajax-url="@Url.Action("GetGrid", "Contatos")">
                                <div class="form-row">
                                    <div class="input-group col-6">
                                        <input name="searchString" type="text" class="form-control" placeholder="Digite um nome ou assunto" arial-label=""
                                               arial-describedby="basic-addon1" value="@ViewData["CurrentFilter"]" />
                                        <div class="input-group-append">
                                            <button class="btn btn-light" type="submit" style="margin-left: 10px">Pesquisar</button>
                                        </div>
                                    </div>
                                </div>
                            </form>

                            <div id="Grid">
                                <partial name="_Grid" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Unipet/Views/Contatos/_Grid.cshtml
@model Unipet.Services.PaginatedList<Unipet.Models.Contato>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]"
                   data-ajax="true" data-ajax-method="get" data-ajax-update="#Grid" data-ajax-mode="replace"
                   data-ajax-url="@Url.Action("GetGrid", "Contatos", new { sortOrder = ViewBag.NameSortParm, searchString = ViewBag.CurrentFilter })">
                    Nome
                    @if (ViewBag.NameSortParm == null)
                    {<i class="fas fa-arrow-up"></i>}
                    @if (ViewBag.NameSortParm == "name_desc")
                    {<i class="fas fa-arrow-down"></i>}
                </a>
            </th>
            <th>E-mail</th>
            <th>Assunto</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Assunto)
            </td>
        </tr>
        }
    </tbody>
</table>
<div class="text-center mt-3">
    @{
        var prevDisable = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }
    <a asp-action="Index" asp-route-pageNumber="@(Model.PageIndex - 1)"
       data-ajax="true" data-ajax-method="get" data-ajax-update="#Grid" data-ajax-mode="replace"
       data-ajax-url="@Url.Action("GetGrid", "Contatos", new { pageNumber = Model.PageIndex - 1, searchString = ViewBag.CurrentFilter})"
       class="btn btn-light @prevDisable">
        Anterior
    </a>
    <a asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 1)"
       data-ajax="true" data-ajax-method="get" data-ajax-update="#Grid" data-ajax-mode="replace"
       data-ajax-url="@Url.Action("GetGrid", "Contatos", new { pageNumber = Model.PageIndex + 1, searchString = ViewBag.CurrentFilter})"
       class="btn btn-light @nextDisabled">
        Próxima
    </a>
</div>